### ISSUE TITLE
Keep reporting this error during startup

### ISSUE THREAD

**Issue by stankawiky** [toshiaki1729/stable-diffusion-webui-text2prompt#3]
========================
ModuleSpec(name='database_loader.py', loader=<_frozen_importlib_external.SourceFileLoader object at 0x7f1dfa3383a0>, origin='/root/autodl-tmp/github/stable-diffusion-webui/extensions/stable-diffusion-webui-text2prompt/scripts/t2p/prompt_generator/database_loader.py')
Error loading script: main.py
Traceback (most recent call last):
  File "/root/autodl-tmp/github/stable-diffusion-webui/modules/scripts.py", line 229, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "/root/autodl-tmp/github/stable-diffusion-webui/modules/script_loading.py", line 13, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/root/autodl-tmp/github/stable-diffusion-webui/extensions/stable-diffusion-webui-text2prompt/scripts/main.py", line 14, in <module>
    _wd_like = dynamic_import('scripts/t2p/prompt_generator/wd_like.py')
  File "/root/autodl-tmp/github/stable-diffusion-webui/extensions/stable-diffusion-webui-text2prompt/scripts/t2p/dynamic_import.py", line 5, in dynamic_import
    return script_loading.load_module(path)
  File "/root/autodl-tmp/github/stable-diffusion-webui/modules/script_loading.py", line 13, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/root/autodl-tmp/github/stable-diffusion-webui/extensions/stable-diffusion-webui-text2prompt/scripts/t2p/prompt_generator/wd_like.py", line 16, in <module>
    dloader = dynamic_import('scripts/t2p/prompt_generator/database_loader.py')
  File "/root/autodl-tmp/github/stable-diffusion-webui/extensions/stable-diffusion-webui-text2prompt/scripts/t2p/dynamic_import.py", line 5, in dynamic_import
    return script_loading.load_module(path)
  File "/root/autodl-tmp/github/stable-diffusion-webui/modules/script_loading.py", line 13, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/root/autodl-tmp/github/stable-diffusion-webui/extensions/stable-diffusion-webui-text2prompt/scripts/t2p/prompt_generator/database_loader.py", line 10, in <module>
    class Database:
  File "/root/autodl-tmp/github/stable-diffusion-webui/extensions/stable-diffusion-webui-text2prompt/scripts/t2p/prompt_generator/database_loader.py", line 11, in Database
    def __init__(self, database_path: str, re_filename: re.Pattern[str]):
TypeError: 'type' object is not subscriptable

**Comment by toshiaki1729** [comment]
The type hint was incompatible with Python<3.9.
May be fixed in the commit c4d8cec126fb0711b6bb5f0c339d87bf8b8932d0
